server:
  port: 8081

spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
#        git:
#          uri: file:///${user.home}/cloud_config_application_properties
  profiles:
    active: native

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/